// Mirror of backend/src/constants/audit-events.ts (single source of truth =
// backend). Kept in sync by backend/tests/constants-sync.test.ts. Used by the
// activity feed to render event names from the audit log.
export const AUDIT_EVENTS = {
  GIT_PUSH: "git.push",
  LFS_DOWNLOAD: "lfs.download",
  LFS_UPLOAD: "lfs.upload",
  AUTH_LOGIN: "auth.login",
  AUTH_LOGOUT: "auth.logout",
  AUTH_REVOKE_ALL: "auth.revoke_all",
  AUTH_CHANGE_PASSWORD: "auth.change_password",
  AUTH_INVITE_ACCEPT: "auth.invite_accept",
  INVITATION_CREATE: "invitation.create",
  INVITATION_REVOKE: "invitation.revoke",
  TOKEN_CREATE: "token.create",
  TOKEN_REVOKE: "token.revoke",
  USER_UPDATE: "user.update",
  USER_RESET_PASSWORD: "user.reset_password",
  USER_DELETE: "user.delete",
  PROJECT_CREATE_WITH_CONNECTION: "project.create_with_connection",
  PROJECT_DELETE: "project.delete",
  PROJECT_BACKUP: "project.backup",
  PROJECT_RESTORE: "project.restore",
  PROJECT_COLLABORATOR_ADD: "project.collaborator_add",
  PROJECT_COLLABORATOR_UPDATE: "project.collaborator_update",
  PROJECT_COLLABORATOR_REMOVE: "project.collaborator_remove",
  STORAGE_CREATE_CONNECTION: "storage.create_connection",
  STORAGE_DELETE_CONNECTION: "storage.delete_connection",
  STORAGE_DELETE_OBJECT: "storage.delete_object",
  EMAIL_UPDATE: "email.update",
  EMAIL_TEST: "email.test",
  BRANCH_CREATE: "branch.create",
  BRANCH_DELETE: "branch.delete",
  PULL_REQUEST_CREATE: "pull_request.create",
  PULL_REQUEST_UPDATE: "pull_request.update",
  PULL_REQUEST_STATUS_CHANGE: "pull_request.status_change",
  PULL_REQUEST_DELETE: "pull_request.delete",
  PULL_REQUEST_MERGE: "pull_request.merge",
  PULL_REQUEST_COMMENT: "pull_request.comment",
  PULL_REQUEST_REVIEW: "pull_request.review",
  PROTECTION_CREATE: "protection.create",
  PROTECTION_UPDATE: "protection.update",
  PROTECTION_DELETE: "protection.delete",
} as const;

export type AuditEvent = (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];
