// Mirror of backend/src/constants/errors.ts (single source of truth = backend).
// Kept in sync by backend/tests/constants-sync.test.ts. Used by the UI to
// branch on API error codes (e.g. confirmation-required flows).
export const ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_PROJECT_NAME: "INVALID_PROJECT_NAME",
  PROJECT_NAME_TAKEN: "PROJECT_NAME_TAKEN",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INVALID_INVITATION: "INVALID_INVITATION",
  DISCONNECT_CONFIRMATION_REQUIRED: "DISCONNECT_CONFIRMATION_REQUIRED",
  RESTORE_BEHIND: "RESTORE_BEHIND",
  BRANCH_EXISTS: "BRANCH_EXISTS",
  INVALID_BRANCH_NAME: "INVALID_BRANCH_NAME",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
