// Audit event names. Single source of truth - audit() call sites reference
// these instead of inline strings.
export const AUDIT_EVENTS = {
  GIT_PUSH: "git.push",
  LFS_DOWNLOAD: "lfs.download",
  LFS_UPLOAD: "lfs.upload",
  AUTH_LOGIN: "auth.login",
  AUTH_LOGOUT: "auth.logout",
  AUTH_REVOKE_ALL: "auth.revoke_all",
  AUTH_CHANGE_PASSWORD: "auth.change_password",
  AUTH_INVITE_ACCEPT: "auth.invite_accept",
  INVITATION_CREATE: "invitation.create",
  INVITATION_REVOKE: "invitation.revoke",
  TOKEN_CREATE: "token.create",
  TOKEN_REVOKE: "token.revoke",
  USER_UPDATE: "user.update",
  USER_RESET_PASSWORD: "user.reset_password",
  USER_DELETE: "user.delete",
  PROJECT_CREATE_WITH_CONNECTION: "project.create_with_connection",
  PROJECT_DELETE: "project.delete",
  PROJECT_BACKUP: "project.backup",
  PROJECT_RESTORE: "project.restore",
  PROJECT_COLLABORATOR_ADD: "project.collaborator_add",
  PROJECT_COLLABORATOR_UPDATE: "project.collaborator_update",
  PROJECT_COLLABORATOR_REMOVE: "project.collaborator_remove",
  STORAGE_CREATE_CONNECTION: "storage.create_connection",
  STORAGE_DELETE_CONNECTION: "storage.delete_connection",
  STORAGE_DELETE_OBJECT: "storage.delete_object",
  EMAIL_UPDATE: "email.update",
  EMAIL_TEST: "email.test",
  BRANCH_CREATE: "branch.create",
  BRANCH_DELETE: "branch.delete",
} as const;
