// Error codes used in API error responses. Single source of truth - every
// route/module references these instead of inline strings.
export const ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_PROJECT_NAME: "INVALID_PROJECT_NAME",
  PROJECT_NAME_TAKEN: "PROJECT_NAME_TAKEN",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INVALID_INVITATION: "INVALID_INVITATION",
  BRANCH_EXISTS: "BRANCH_EXISTS",
  INVALID_BRANCH_NAME: "INVALID_BRANCH_NAME",
} as const;
