import { marked, Renderer } from "marked";

function escapeHtml(input: string): string {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

// Render repo README markdown. README content is untrusted repository data:
// raw HTML passthrough is escaped via the renderer, so the marked output
// cannot inject scripts. Everything else is generated by marked from the
// markdown source itself (safe by construction).
export function renderMarkdown(md: string): string {
  const renderer = new Renderer();
  renderer.html = ({ text }) => escapeHtml(text);
  return marked.parse(md, { renderer, async: false }) as string;
}
